---
title: "64060_Assignment_1"
author: "Joseph Demore"
date: "`r Sys.Date()`"
output: html_document
---
# Q1, Q2: Import dataset
### Best Steam Game sales, top 1500 lines. From Kaggle.
```{r}
# Source: Kaggle { see below }
# https://www.kaggle.com/datasets/alicemtopcu/top-1500-games-on-steam-by-revenue-09-09-2024?resource=download

TopSales <- read.csv("Steam_2024_bestRevenue_1500.csv", header = TRUE)
colnames(TopSales)
```
# Q3
### Quantitative Variables
```{r}
# Quantitative Vars in this set are:
# price, revenue, reviewScore, copiesSold, avgPlaytime
# Printed out summary for -some- as requested. Others would just be rinse-repeat of same func.
summary(TopSales$price)
summary(TopSales$revenue)
summary(TopSales$reviewScore)
```
### Qualitative Variables
```{r}
# Qualitative vars in this set are:
# name, releaseDate (stored as char. could be converted to qual with some effort.), publisherClass, publishers, developers, steamId (this is a number but it's still qual)
summary(TopSales$publisherClass)
table(TopSales$publisherClass)

summary(TopSales$releaseDate)
table(TopSales$releaseDate)
```

# Q4
### Transformation from qualitative DTF to quantitative DTF
### I like to be different.

```{r}
# Check existing order of the data.frame & pull first row
summary(TopSales$releaseDate)
head(TopSales$releaseDate)
# Reorder for date time format as day-month-year (for sorting with hist or sort funcs)
TopSales$releaseDate <- as.Date(TopSales$releaseDate, format = "%d-%m-%Y")
# Trust but verify, let's use that test driven development.
head(TopSales$releaseDate)
```

### Transformation from qualitative publisherClass to numeric / enums

```{r}
summary(TopSales$publisherClass)
TopSales$publisherClass_enum <- as.numeric(factor(TopSales$publisherClass))
summary(TopSales$publisherClass_enum)
```
# Q5
### Plot Quant

```{r}
# Just a boring printout of sales by revenue bucket. Log10'd to make it readable, it's quite ugly without.
hist(log10(TopSales$revenue))
```


### Plot Qual

```{r}
# applies Mean func to the table. Easier to plot it out this way.
avg_by_class <- tapply(TopSales$revenue, TopSales$publisherClass, mean)

barplot(avg_by_class, main = "Avg Revenue by Publisher Class", xlab = "Publisher Class", ylab = "Avg Revenue")
```


### Plot Scatter

```{r}
# Interestingly enough; the highest selling games didn't have the most average playtime.
plot(TopSales$avgPlaytime, TopSales$revenue, main="Revenue Vs. Avg Playtime", xlab="Avg Playtime", ylab="Revenue")
```

